FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["SmartLedger.API.csproj", "."]
RUN dotnet restore "./SmartLedger.API.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "SmartLedger.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SmartLedger.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SmartLedger.API.dll"]